apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: landing
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: landing
      spec:
        replicas: 2
        template:
          spec:
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      labelSelector:
                        matchLabels:
                          app: landing
                      topologyKey: kubernetes.io/hostname
            containers:
              - name: landing
                image: registry.overmind-platform.svc:5000/landing:0.3.0
                imagePullPolicy: Always
